### ISSUE TITLE
数据库与数据导入进去之后 登录不成功 

### ISSUE THREAD

**Issue by Leiss0723** [ningzichun/student-management-system#3]
数据库与数据导入进去之后 登录不成功  学生的账号密码都输入正确的 但是输入登陆的时候就是不行！！！  救命！大佬能不能加我vx：1822345456 或者留个联系方式 我加你！

**Comment by ningzichun** [comment]
你好，

在导入example.sql之前修改 user_admin 的数据，你可以修改成
```
INSERT INTO `user_admin` (`adminID`, `adminName`, `pwd`) VALUES
('admin', 'A先生', '21232f297a57a5a743894a0e4a801fc3');
```
这样用户名和密码都是 admin

你始终可以修改 user_admin 表中的 adminID 和 pwd，它分别代表管理员账户的登录 id 和 密码的md5值。
