### ISSUE TITLE
学生选课查询不了 报错

### ISSUE THREAD

**Issue by Leiss0723** [ningzichun/student-management-system#6]
Notice: Undefined index: tname in D:\student-management-system-master\admin\fun\getChoose.php on line 40
选课查询的时候就报这个错误 但是我检查了这个表我是已经创建了课程并且tname数据也是对的 （对之前我问的一些家庭式问题深感抱歉，能不能帮忙解决一下现在的）

**Comment by ningzichun** [comment]
你好，经过测试，请将程序运行在PHP7.4或以下的版本，示例数据可以运行。在PHP8中会产生些提示，你可以修改代码到新标准，或忽略提示。
